# Generated by Django 2.2.2 on 2019-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_column='Created')),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=512, null=True)),
                ('url_id', models.IntegerField(blank=True, db_column='Url_Id', null=True)),
                ('url', models.TextField(blank=True, db_column='Url', null=True, unique=True)),
            ],
            options={
                'db_table': 'spider',
                'managed': False,
            },
        ),
    ]
