# Generated by Django 2.2.2 on 2019-08-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappingsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spider',
        ),
    ]
